---
layout: post
title: "Promise"
date: 2021-11-14 19:23:27 +0900
category: javascript
tags: javascript
image:
  path: https://images.unsplash.com/photo-1523966211575-eb4a01e7dd51?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=710&q=80
---

# Promise

### `코어 자바스크립트(정재남 저)` 책을 기본으로 하여 자바스크립트를 공부하면서 내용을 정리하고자 한다.

---

# 04 Callback function

<br>

## 🖇 Promise

### **`Promise`** 는 자바스크립트에서 비동기 작업을 간편하게 할 수 있게 도와주는 객체이다.

비동기 작업을 수행하다가 작업이 성공적으로 이루어지면 성공의 결과값을 반환하지만, 예상치 못한 상황이 발생하여 작업이 실패하면 error를 반환한다.

<br>

## 🪄 Promise의 주요 POINT!

## 1.**State**

> **Promise** 는 3가지 상태를 가진다.

<br>

🪡 **Pending** : 비동기 처리가 아직 진행되지 않은 상태 [`resolve 또는 reject 함수가 실행되지 않음`]

🪡 **Fulfulled** : 비동기 처리가 수행된 상태 (성공) [`resolve 함수 실행`]

🪡 **Rejected** : 비동기 처리가 수행된 상태 (실패) [`reject 함수 실행`]

<br>

![promiseFlow](https://user-images.githubusercontent.com/79234473/139370123-69734ba7-fd54-4906-a05d-acdcbc72d539.png)

<br>

## 2. **Producer** vs **Consumer**

## 🪃 **Producer** <br>

### 💡 **NOTICE**

**Promise** 는 생성한 즉시 실행된다. 자동적으로~

![promise1](https://user-images.githubusercontent.com/79234473/141677944-a6f85468-0b5e-44be-b057-7c003ef7c3f8.png)

## 🪃 **Consumers**<br>

> **then, catch, finally : 결과값을 받아온다.**

![promise2](https://user-images.githubusercontent.com/79234473/141677975-e468815d-7428-400a-bd7b-1feed8cc0b85.png)

### 📎 **then**

```
then 메소드는 두 개의 콜백 함수를 인자로 전달 받는다.

첫 번째 콜백 함수는 성공(fulfilled, resolve 함수가 호출된 상태) 시 호출되고

두 번째 함수는 실패(rejected, reject 함수가 호출된 상태) 시 호출된다.
```

![promise3](https://user-images.githubusercontent.com/79234473/141677976-884b4d1c-b74d-4c07-b7d0-a5e8e07a850d.png)

### 📎 **catch**

```
예외(비동기 처리에서 발생한 에러와 then 메소드에서 발생한 에러)가 발생하면 호출된다.
```

![promise4](https://user-images.githubusercontent.com/79234473/141677977-411eaaec-13ed-4437-8038-47e7de8775a4.png)

### 📎 **finally**

```
Promise가 처리되면 충족되거나 거부되는지 여부에 관계없이 지정된 콜백 함수가 실행된다.

이것은 Promise가 성공적으로 실행되었는지 거절되었는지에 관계없이 Promise가 처리 된 후에 코드가 무조건 한 번은 실행되게 한다.
```

![promise5](https://user-images.githubusercontent.com/79234473/141678000-83b753f4-a9f7-47e0-8ca2-1416cc721d0c.png)

### 👉🏼 **For Example**

![promise6](https://user-images.githubusercontent.com/79234473/141678132-4bdb38e2-0991-4283-a07d-05fe5e3e95ed.png)

위의 예시를 보면, 좀 더 이해가 될 듯 하다.

변수 complete를 가지고 성공, 실패를 확인할 수 있는데, 지금 변수의 값이 false 임으로 reject 함수가 실행될 것이다.

결과는 `value -> something wrong!`

변수 complete가 true 라면 resolve 함수가 실행되고,

결과는 `value -> result!` 가 나올 것이다.

그리고 변수 complete가 무엇이든 간에

결과값으로 `finally` 는 무조건 출력된다.

---

## ⛓ **Promise Chaining**

**Promise** 는 여러 개의 **Promise** 를 연결하여 사용할 수 있다.

### 👉🏼 **For Example 1**

![promise7](https://user-images.githubusercontent.com/79234473/141678136-56bf02d3-017f-4b5d-93a1-53742fc601dd.png)

결과값을 받아 바로 다음 **.then** 으로 넘겨주는 형식으로 진행된다.

<br>

### 👉🏼 **For Example 2**

![promise8](https://user-images.githubusercontent.com/79234473/141678137-44576dfa-24b8-4e0d-8a63-4dfa2a64ca73.png)

<br>

### 자, 그럼 콜백함수에서 콜백지옥이 발생하던 코드를 Promise로 변경해보자.

![promise9](https://user-images.githubusercontent.com/79234473/141678139-9f803933-6383-46c3-bb26-28e7c566b194.png)

좀 더 간단하게 코드를 바꾸면,

![promise10](https://user-images.githubusercontent.com/79234473/141678142-d936d84e-65e6-4e23-884e-84b33477bf2b.png)

<br>

---

## 💁🏻‍♀️ **Error handling**

**Promise** 에서는 2가지 방법으로 에러처리가 가능하다.

첫번째는 then 메소드의 두번째 콜백함수를 사용하는 방법이고, 두번째 방식은 catch 메소드를 사용하는 방법이다.

그러나, 첫번째 방법의 에러처리는 가독성이 좋지 않을 뿐더러, then 메소드의 첫번째 콜백 함수에서 에러가 나면 잡아내질 못한다.

때문에 **Promise** 에러처리는 두번째 방식인 catch 메소드를 사용하는 것이 권장된다.

<br>

### 👉🏼 **For Example**

👩🏻‍💻 then 메소드의 두번째 콜백 함수 사용하는 에러처리

![promise11](https://user-images.githubusercontent.com/79234473/141678143-f75691af-fd2c-4871-9224-87c100b066fa.png)

<br>

🧑🏻‍💻 catch 메소드를 통한 에러처리

![promise12](https://user-images.githubusercontent.com/79234473/141678145-95a0878d-92ab-469a-baa4-17d0ea819ab3.png)

2가지 경우 다 결과는 동일하다.

<br>

### 그럼, 다음의 경우를 살펴보자.

<br>

👩🏻‍💻 then 메소드의 두번째 콜백 함수 사용하는 에러처리 2

![promise13](https://user-images.githubusercontent.com/79234473/141678148-2f642c67-6d0c-4aac-8f58-78a68ddef638.png)

then 메소드의 첫번째 콜백함수 내부에서 일어나는 에러를 잡아내지 못한다.

<br>

🧑🏻‍💻 catch 메소드를 통한 에러처리 2

![promise14](https://user-images.githubusercontent.com/79234473/141678149-236403e4-6038-49d2-970e-f2cb59affb48.png)

catch 메소드를 사용하는 경우 에러처리가 가능하다.

<br>

[코드 참고하려면](<https://github.com/Gryffindor0ne/studyNote/blob/main/JavaScript/Callback2(promise).md>)

<br>

👉🏻 다음 장에서 이어서 설명 👉🏻

---

## 참고자료

- [프로미스](https://poiemaweb.com/es6-promise)

- [드림코딩 엘리\_ Javascript promise](https://www.youtube.com/watch?v=JB_yU6Oe2eE)

- [MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise)
